version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      # security отключен для разработки
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    container_name: kibana
    image: kibana:8.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # security отключен для разработки
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  app:
    build: .
    container_name: app
    image: app
    environment:
      ES_ADDRESSES: "http://elasticsearch:9200"
      # security отключен для разработки
      ES_USERNAME: ""
      ES_PASSWORD: ""
      ES_CONN_TIMEOUT: "5s"
      ES_CONN_ATTEMPTS: "10"
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - .env

volumes:
  es-data: